services:
  rabbitmq:
    image: 'rabbitmq:3-management'
    hostname: 'rabbitmq'
    container_name: 'rabbitmq-wpp'
    environment:
      RABBITMQ_DEFAULT_USER: 'user'
      RABBITMQ_DEFAULT_PASS: 'password'
    ports:
      - '5671:5672' # Porta padrão do RabbitMQ
      - '15671:15672' # Porta da interface de gerenciamento web